server:
  port: 9001
spring:
  application:
    name: gatewat-service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    name:
      path: /**
      service-id: eureka-client