server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: eureka-service
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    eureka-server-u-r-l-context: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true